import type { Metadata } from "next";
import { Quantico as QuanticoFont, Questrial as QuestrialFont, Rasa as RasaFont, Rammetto_One as RammettoOneFont, Inter as InterFont, Racing_Sans_One as RacingSansOneFont  } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";

const Quantico = QuanticoFont({
  variable: "--font-quantico",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const Questrial = QuestrialFont({
  variable: "--font-questrial",
  subsets: ["latin"],
  weight: ["400"],
});

const Rasa = RasaFont({
  variable: "--font-rasa",
  subsets: ["latin"],
  weight: ["400"],
});

const RammettoOne = RammettoOneFont({
  variable: "--font-rammettoOne",
  subsets: ["latin"],
  weight: ["400"]
})

const Inter = InterFont({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400"]
})

const Racing_Sans_One = RacingSansOneFont({
  variable: "--font-racingSansOne",
  subsets: ["latin"],
  weight: ["400"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Quantico.variable} ${Questrial.variable} ${Rasa.variable} ${RammettoOne.variable} ${Inter.variable} ${Racing_Sans_One.variable}  antialiased overflow-x-hidden`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
