import type { Metadata } from "next";
import { Quantico as QuanticoFont, Questrial as QuestrialFont, Rasa as RasaFont } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";

const Quantico = QuanticoFont({
  variable: "--font-quantico",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const Questrial = QuestrialFont({
  variable: "--font-questrial",
  subsets: ["latin"],
  weight: ["400"],
});

const Rasa = RasaFont({
  variable: "--font-rasa",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Quantico.variable} ${Questrial.variable} ${Rasa.variable}  antialiased overflow-x-hidden`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
